---
title: "User Guide"
author: "Pedro J. Aphalo"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{User Guide}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Introduction

## Stats

```{r}
library(ggplot2)
library(photobiology)
library(ggspectra)
```

```{r setup, include = FALSE, eval = FALSE}
library(svglite)
knitr::opts_chunk$set(
  dev = "svglite",
  fig.ext = ".svg"
)
```

```{r}
library(knitr)
opts_chunk$set(fig.path = 'figure/pos-', fig.align = 'center', fig.show = 'hold',
               fig.width = 7, fig.height = 4)
options(warnPartialMatchArgs = FALSE)
```

```{r}
two_suns.spct <- rbindspct(list(sun1 = sun.spct, sun2 = sun.spct * 2))
```


### Peaks and valleys

```{r}
ggplot(sun.spct, aes(w.length, s.e.irrad)) + geom_line() + 
  stat_peaks()
```

```{r}
ggplot(sun.spct, aes(w.length, s.e.irrad)) + geom_line() + 
  stat_valleys()
```

```{r}
ggplot(sun.spct, aes(w.length, s.e.irrad)) + geom_line() + 
  stat_peaks(span = NULL, geom = "vline", linetype = "dotted") +
  stat_peaks(span = NULL, geom = "hline", linetype = "dotted")
```

```{r}
ggplot(sun.spct, aes(w.length, s.e.irrad)) + geom_line() + 
  stat_peaks(span = 21, shape = 4, color = "red", size = 2)
```

```{r}
ggplot(sun.spct, aes(w.length, s.e.irrad)) + geom_line() + 
  stat_peaks(span = 21, geom = "text")
```

```{r}
ggplot(sun.spct, aes(w.length, s.e.irrad)) + geom_line() + 
  stat_peaks(span = 21, geom = "text", aes(label = ..y.label..))
```

```{r}
ggplot(sun.spct, aes(w.length, s.e.irrad)) + geom_line() + 
  stat_peaks(span = NULL) +
  stat_peaks(span = NULL, geom = "text", vjust = -0.5, size = 2.5,
             y.label.fmt = "%.3f",
             aes(label = paste(..y.label.., "at", ..x.label.. , "nm")))
```

```{r}
ggplot(sun.spct, aes(w.length, s.e.irrad)) + geom_line() + 
  stat_peaks(span = 21, geom = "point", colour = "red") +
  stat_valleys(span = 21, geom = "point", colour = "blue") +
  stat_peaks(span = 51, geom = "text", colour = "red", 
             vjust = -0.3, label.fmt = "%3.0f nm") +
  stat_valleys(span = 51, geom = "text", colour = "blue", 
               vjust = 1.2, label.fmt = "%3.0f nm")
```

```{r}
ggplot(two_suns.spct, aes(w.length, s.e.irrad, color = spct.idx)) +
  geom_line() + 
  stat_peaks(span = NULL, color = "black") +
  stat_peaks(span = NULL, geom = "text", vjust = -0.5, size = 3,
             y.label.fmt = "%.3f", color = "black", 
             aes(label = paste(..y.label.., "at", ..x.label.. , "nm"))) +
  facet_grid(spct.idx~.)
```

## Color from wavelength

```{r}
ggplot(sun.spct, aes(w.length, s.e.irrad)) + geom_line() +
  stat_color() + scale_color_identity()
```

```{r}
ggplot(sun.spct, aes(w.length, s.e.irrad)) + geom_line() +
  stat_color(shape = 21, color = "black") + scale_fill_identity()
```

```{r}
ggplot(sun.spct, aes(w.length, s.e.irrad)) + 
  stat_color(geom = "bar") + stat_color(shape = 21, color = "black", stroke = 1.2, fill = "white") +
  scale_fill_identity() + scale_color_identity() + theme_bw()
```

```{r}
ggplot(two_suns.spct, aes(w.length, s.e.irrad, shape = spct.idx)) +
  stat_color() + scale_color_identity() +
  geom_line() + 
  facet_grid(spct.idx~., scales = "free_y")
```

## Integral and similar summaries

```{r}
ggplot(sun.spct, aes(w.length, s.e.irrad)) + geom_line() +
  stat_integral()
```

```{r}
ggplot(sun.spct, aes(w.length, s.e.irrad)) + geom_line() +
  stat_integral(range = c(300,500), label.fmt = "%.3f", color = "red")
```

```{r}
ggplot(sun.spct, aes(w.length, s.e.irrad)) +
  stat_integral(geom = "hline", color = "red") +
  geom_line() + stat_integral(label.fmt = "Mean = %.3f", color = "red", vjust = -0.3)
```

```{r}
ggplot(two_suns.spct, aes(w.length, s.e.irrad, color = spct.idx)) +
  stat_integral(geom = "hline") +
  geom_line() + stat_integral(label.fmt = "Mean = %.3f", vjust = -0.3, show.legend = FALSE)
```

```{r}
ggplot(sun.spct, aes(w.length, s.e.irrad)) +
  stat_integral(range = c(400,500), geom = "rect", alpha = 0.5) +
  geom_line() + 
  stat_integral(range = c(400,500), label.fmt = "Mean = %.3f", vjust = 30, geom = "text")
```

```{r}
ggplot(two_suns.spct, aes(w.length, s.e.irrad, color = spct.idx)) +
  stat_integral(geom = "hline") +
  geom_line() + 
  stat_integral(label.fmt = "Mean = %.3f", vjust = 1.2, show.legend = FALSE) +
  facet_grid(spct.idx~.)
```

```{r}
ggplot(two_suns.spct, aes(w.length, s.e.irrad, color = spct.idx)) +
  stat_integral(geom = "hline") +
  geom_line() + 
  stat_integral(label.fmt = "Mean = %.3f", vjust = 1.2, show.legend = FALSE) +
  facet_grid(spct.idx~., scales = "free_y")
```
