---
title: "Test with other ggplot extensions"
author: "Pedro J. Aphalo"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{est with other ggplot extensions}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Setup

```{r}
library(ggplot2)
library(photobiology)
library(photobiologyWavebands)
library(ggspectra)
library(photobiologyPlants)
```

```{r, include=FALSE, echo=FALSE}
library(knitr)
opts_chunk$set(fig.path = 'figure/pos-', fig.align = 'center', fig.show = 'hold',
               fig.width = 7, fig.height = 4)
options(warnPartialMatchArgs = FALSE)
```

We bind two spectra, to later on demonstrate grouping.

```{r}
two_suns.spct <- rbindspct(list(sun1 = sun.spct, sun2 = sun.spct * 2))
```

## ggrepel

```{r}
library(ggrepel)

```

```{r}
ggplot(sun.spct) + geom_line() + 
  ylim(NA, 1) +
  stat_peaks(span = 21, geom = "text_repel", color = "red", min.segment.length = 0,
             box.padding = 0.05,
             position = position_nudge_keep(y = rel(0.03)), size = rel(3.5), hjust = 0.5)
```

```{r}
ggplot(sun.spct) + geom_line() + 
  stat_peaks(span = 21, geom = "label_repel", fill = "white",
             min.segment.length = 0,
             box.padding = 0.05,
             position = position_nudge_keep(y = rel(0.03)), size = rel(2.5)) +
  ylim(NA, 1) +
  scale_fill_identity()
```

```{r}
ggplot(two_suns.spct) + geom_line() + 
  stat_peaks(span = 21, geom = "label_repel", fill = "white",  
             min.segment.length = 0,
             box.padding = 0.05,
             position = position_nudge_keep(y = 0.15), size = rel(2)) +
  ylim(NA, 2) +
  scale_fill_identity() +
  facet_wrap(~spct.idx)
```

## cowplot

```{r}
library(cowplot)
theme_set(theme_cowplot(10))
```

```{r}
autoplot(sun.spct, unit.out = "photon")
```

```{r}
autoplot(sun.spct, w.band = VIS_bands(), unit.out = "photon")
```

```{r, fig.width = 7, fig.height = 15}
theme_set(theme_cowplot(10))
p1 <- autoplot(sun.spct, unit.out = "photon")
p2 <- autoplot(yellow_gel.spct)
p3 <- autoplot(Solidago_altissima.mspct$lower_adax)
plot_grid(p1, p2, p3, ncol = 1, align = "V")
```

```{r, fig.width = 7, fig.height = 15}
theme_set(theme_grey(10))
p1 <- autoplot(sun.spct, unit.out = "photon")
p2 <- autoplot(yellow_gel.spct)
p3 <- autoplot(Solidago_altissima.mspct$lower_adax)
plot_grid(p1, p2, p3, ncol = 1, align = "V")
```
